// DO NOT EDIT THIS FILE!!
// Duplicate it and make changes in the duplicated

import p5Types from "p5";
import {
  CanvasBase,
  ICanvasBase,
  ICanvasBaseArgs,
} from "../private/CanvasBase";

// if you need any public properties add them here
export interface ICanvas extends ICanvasBase {
}

// add any additional args here
export interface ICanvasArgs extends ICanvasBaseArgs {
}

export class Canvas extends CanvasBase implements ICanvas {
  is3D = true;



  // create a draw function to generate your own animation!
  public draw = () => {
    this.p5.background(100);
    this.p5.fill(50);
    this.p5.push();
    this.p5.translate(275, -475, -490);
    // this.p5.rotateY(1.25);
    // this.p5.rotateX(-0.9);
    this.p5.box(100);
    this.p5.pop();
    this.p5.translate(100, 0, 0);
    this.p5.rotateY(Math.PI / 4);
    // this.p5.rotateX(Math.PI / 4);
    this.p5.rotateZ(-Math.PI / 10);
    this.p5.box(60);
  };
}

// export a hot canvas which initializes your canvas
// in order to get hot reloads when you make changes
export const hotCanvas = new Canvas();
